version: "3.7"

networks:
  default:
    external:
      name: super-rede

services:
  database_postgres:
    image: postgres
    container_name: database_postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentalx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app


volumes:
  pgdata:
    driver: local