version: "3.7"

services:
  database_service:
    image: postgres
    container_name: database_service
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentalx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_service
    depends_on:
      - database_service


volumes:
  pgdata:
    driver: local