version: "3.7"

networks:
  default:
    external:
      name: super-rede

services:
  app:
    build: .
    container_name: rentalx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app


volumes:
  pgdata:
    driver: local